### ISSUE TITLE
"open file of certain revision" in magit configuration code seems redundant 

### ISSUE THREAD

**Issue by dankeyy** [redguardtoo/vc-msg#7]
Hey, in the README you have this part of the snippet for integration with magit:
```elisp
(eval-after-load 'vc-msg-git
  '(progn
     ;; show code of commit
     (setq vc-msg-git-show-commit-function 'magit-show-commit)
     ;; open file of certain revision
     (push '("m"
             "[m]agit-find-file"
             (lambda ()
               (let* ((info vc-msg-previous-commit-info)
                      (git-dir (locate-dominating-file default-directory ".git")))
                 (magit-find-file (plist-get info :id )
                                  (concat git-dir (plist-get info :filename))))))
           vc-msg-git-extra)))
```
But the second part (find-file) seems unnecessary.
You already do almost the exact same thing here- https://github.com/redguardtoo/vc-msg/blob/master/vc-msg-git.el#L212-L221

So if a person adds this snippet to their configuration, they'll most certainly be using magit so `(fboundp 'magit-find-file)` will evaluate to `t`, the symbol will be pushed twice and so they'll see two the same option twice when calling `vc-msg-show`.

![image](https://user-images.githubusercontent.com/74069206/194043355-f200e7c6-9517-4609-8980-5d6003bc4bd4.png)

Might wanna clarify that in the README.
Anyways thanks for the package, it's great.

**Comment by redguardtoo** [comment]
027fefa doc (Chen Bin)
