### ISSUE TITLE
Is it possible to customize colors?

### ISSUE THREAD

**Issue by LionyxML** [redguardtoo/vc-msg#8]
Hello there!

I love this package! It is really useful on my workflow, I use it multiple times a day, daily. Thanks!

Is it possible to customize the colors?

<img width="591" alt="image" src="https://github.com/redguardtoo/vc-msg/assets/16169950/7f5965f9-f727-43f4-8c8a-8c90c0db8721">

It kind of breaks my theming config.

I tried `M-x customize-faces` but there's no auto complete for `vc-msg` and `M-x customize-group vs-msg` offers no face/colors options.

Does it derive it's colors from somewhere else or is it just using some sort of Emacs default?

Thanks!

**Comment by redguardtoo** [comment]
It uses https://github.com/auto-complete/popup-el  You can set up font face of popup through this package.

**Comment by LionyxML** [comment]
Thanks @redguardtoo! 

For further reference, the `popup-tip-face` is the one to be customized. Worked like a charm. :)
